language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_62f3167d5387_key -iv $encrypted_62f3167d5387_iv -in id_rsa.enc -out id_rsa -d
install:
  - pip install mkdocs
script:
  - mkdocs build --clean
after_success:
  # Add the ssh key
  - eval "$(ssh-agent)"
  - chmod 600 id_rsa
  - ssh-add id_rsa
deploy:
  provider: pages
  skip-cleanup: true
  on:
    branch: mkdocs
  local-dir: site
  target-branch: master
